services:
  - type: web
    name: minimal-test
    env: node
    plan: free
    root: .
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
