services:
  - type: web
    name: minimal-test
    env: node
    plan: free
    root: .
    buildCommand: |
      yarn install
      yarn build
      ls -l
      ls -l dist
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
